name: DistrictRP
version: 2.1.8
main: dev.breach.DistrictRP.DistrictRP
api-version: '1.20'
author: breachato
description: Roleplay Core made by breachato
load: POSTWORLD
softdepend:
  - LuckPerms
  - TAB
  - SkinsRestorer
  - Multiverse-Core
  - PlaceholderAPI
  - CoreProtect
  - WorldGuard
  - WorldEdit

commands:
  districtrp:
    usage: /districtrp [sub-comando]
    aliases: [drp]
    permission: DistrictRP.use
  spawn:
    usage: /spawn [world]
    permission: DistrictRP.spawn
  setspawn:
    usage: /setspawn [world]
    permission: DistrictRP.setspawn
  back:
    usage: /back
    permission: DistrictRP.back
  fly:
    usage: /fly [player]
    permission: DistrictRP.fly
  god:
    usage: /god [player]
    permission: DistrictRP.god
  speed:
    usage: /speed <0-10> [player]
    permission: DistrictRP.speed
  gms:
    usage: /gms [player]
    permission: DistrictRP.gamemode
  gmc:
    usage: /gmc [player]
    permission: DistrictRP.gamemode
  gma:
    usage: /gma [player]
    permission: DistrictRP.gamemode
  gmsp:
    usage: /gmsp [player]
    permission: DistrictRP.gamemode
  msg:
    usage: /msg <player> <messaggio>
    permission: DistrictRP.msg
  reply:
    usage: /reply <messaggio>
    aliases: [r]
    permission: DistrictRP.msg
  nick:
    usage: /nick <nick> [player]
    permission: DistrictRP.nick
  invsee:
    usage: /invsee <player>
    permission: DistrictRP.invsee
  enderchest:
    usage: /enderchest [player]
    aliases: [ec]
    permission: DistrictRP.enderchest
  clear:
    usage: /clear [player]
    permission: DistrictRP.clear
  tphere:
    usage: /tphere <player>
    permission: DistrictRP.tphere
  tpall:
    usage: /tpall
    permission: DistrictRP.tpall
  clearchat:
    usage: /clearchat
    aliases: [chatclear]
    permission: DistrictRP.clearchat
  build:
    usage: /build
    aliases: [assets]
    permission: DistrictRP.buildworld
  mondo:
    usage: /mondo <sub>
    aliases: [mondi]
    permission: DistrictRP.mondo
  vanish:
    usage: /vanish [player]
    aliases: [v]
    permission: DistrictRP.vanish
  staffmode:
    usage: /staffmode
    aliases: [sm, staff]
    permission: DistrictRP.staffmode
  scale:
    description: Cambia la scala del player
    usage: /scale <valore> [player]
    permission: DistrictRP.scale
  azione:
    usage: /azione <testo>
    aliases: [a]
  bisbiglio:
    usage: /bisbiglio <testo>
  urlo:
    usage: /urlo <testo>
  chatsym:
    usage: /chatsym <sub>
    permission: DistrictRP.staffchatsym
  emoji:
    usage: /emoji
  stafflist:
    usage: /stafflist
    aliases: [sl]
  plot:
    description: Gestione plot (creative mode)
    usage: /plot <sub>
    aliases: [ p, plots ]
    permission: DistrictRP.plot.use
  ticket:
    usage: /ticket <sub>
    aliases: [aiuto]
  supporto:
    usage: /supporto
  appuntamento:
    usage: /appuntamento
    aliases: [appuntamenti]
  stuck:
    usage: /stuck
    aliases: [bloccato]
  playtime:
    usage: /playtime [player]
    aliases: [info]
  logs:
    usage: /logs <modulo> [player] [pagina]
    permission: DistrictRP.logs
  protection:
    usage: /protection
    aliases: [prot]
    permission: DistrictRP.protection.admin
  warp:
    usage: /warp <nome>
    permission: DistrictRP.warp.use
  setwarp:
    usage: /setwarp <nome> [permesso]
    permission: DistrictRP.warp.manage
  delwarp:
    usage: /delwarp <nome>
    permission: DistrictRP.warp.manage
  chat:
    aliases: [c]
    usage: /chat <nome> [messaggio]
  chatgate:
    usage: /chatgate [sub]
    permission: chatgate.use
    aliases: [cg]
  wipe:
    usage: /wipe <player> <tipo> [confirm]
    permission: DistrictRP.wipe
  profilo:
    usage: /profilo <sub> <player> [valore]
    aliases: [profile]
    permission: DistrictRP.profile.admin
  appuntamento_select_reparto:
    usage: /appuntamento_select_reparto
  appuntamento_select_giorno:
    usage: /appuntamento_select_giorno
  appuntamento_fascia_page:
    usage: /appuntamento_fascia_page
  appuntamento_select_orario:
    usage: /appuntamento_select_orario
  ticket_quickreplies:
    usage: /ticket_quickreplies
  ticket_cancel_comment:
    usage: /ticket_cancel_comment
  supporto_continua:
    usage: /supporto_continua

permissions:
  DistrictRP.profile.admin:
    default: op
  DistrictRP.plot.use:
    default: true
  DistrictRP.plot.admin:
    default: op
  DistrictRP.plot.unlimited:
    default: op
  DistrictRP.stuck.admin:
    default: op
  DistrictRP.vip:
    default: false
  DistrictRP.vipplus:
    default: false
  DistrictRP.mvp:
    default: false
  DistrictRP.mvpplus:
    default: false
  DistrictRP.wipe:
    default: op
  DistrictRP.warp.use:
    default: true
  DistrictRP.warp.manage:
    default: op
  DistrictRP.warp.bypass:
    default: op
  DistrictRP.scale:
    default: op
  DistrictRP.scale.others:
    default: op
  chatgate.use:
    default: op
  chatgate.reload:
    default: op
  chatgate.create:
    default: op
  chatgate.delete:
    default: op
  chatgate.antispam.bypass:
    default: op
  DistrictRP.*:
    default: op
    children:
      DistrictRP.staff: true
      DistrictRP.admin: true
  DistrictRP.staff:
    default: op
    children:
      DistrictRP.vanish: true
      DistrictRP.vanish.see: true
      DistrictRP.vanish.others: true
      DistrictRP.staffmode: true
      DistrictRP.staffmode.tprandom: true
      DistrictRP.staffmode.invsee: true
      DistrictRP.staffmode.tptarget: true
      DistrictRP.staff.notify: true
      DistrictRP.use: true
      DistrictRP.fly: true
      DistrictRP.fly.others: true
      DistrictRP.god: true
      DistrictRP.god.others: true
      DistrictRP.speed: true
      DistrictRP.speed.others: true
      DistrictRP.gamemode: true
      DistrictRP.invsee: true
      DistrictRP.enderchest.others: true
      DistrictRP.clear.others: true
      DistrictRP.tphere: true
      DistrictRP.tpall: true
      DistrictRP.clearchat: true
      DistrictRP.ticket.staff: true
      DistrictRP.staffchatsym: true
  DistrictRP.admin:
    default: op
    children:
      DistrictRP.back: true
      DistrictRP.setspawn: true
      DistrictRP.buildworld: true
      DistrictRP.mondo: true
      DistrictRP.mondo.bypass: true
      DistrictRP.logs: true
      DistrictRP.protection.admin: true
      DistrictRP.protection.bypass: true
      DistrictRP.clearchat.bypass: true
      DistrictRP.warp.manage: true
      DistrictRP.warp.bypass: true
      DistrictRP.plot.admin: true
      DistrictRP.plot.unlimited: true
  DistrictRP.vanish:
    default: op
  DistrictRP.vanish.see:
    default: op
  DistrictRP.vanish.others:
    default: op
  DistrictRP.staffmode:
    default: op
  DistrictRP.staffmode.tprandom:
    default: op
  DistrictRP.staffmode.invsee:
    default: op
  DistrictRP.staffmode.tptarget:
    default: op
  DistrictRP.staff.notify:
    default: op
  DistrictRP.use:
    default: op
  DistrictRP.spawn:
    default: true
  DistrictRP.setspawn:
    default: op
  DistrictRP.back:
    default: op
  DistrictRP.fly:
    default: op
  DistrictRP.fly.others:
    default: op
  DistrictRP.god:
    default: op
  DistrictRP.god.others:
    default: op
  DistrictRP.speed:
    default: op
  DistrictRP.speed.others:
    default: op
  DistrictRP.gamemode:
    default: op
  DistrictRP.msg:
    default: true
  DistrictRP.nick:
    default: op
  DistrictRP.invsee:
    default: op
  DistrictRP.enderchest:
    default: true
  DistrictRP.enderchest.others:
    default: op
  DistrictRP.clear:
    default: op
  DistrictRP.clear.others:
    default: op
  DistrictRP.tphere:
    default: op
  DistrictRP.tpall:
    default: op
  DistrictRP.clearchat:
    default: op
  DistrictRP.clearchat.bypass:
    default: op
  DistrictRP.buildworld:
    default: op
  DistrictRP.mondo:
    default: op
  DistrictRP.mondo.bypass:
    default: op
  DistrictRP.staffchatsym:
    default: op
  DistrictRP.emojiaccess:
    default: true
  DistrictRP.logs:
    default: op
  DistrictRP.ticket.staff:
    default: op
  DistrictRP.reparto.generale:
    default: op
  DistrictRP.reparto.tecnico:
    default: op
  DistrictRP.reparto.edilizia:
    default: op
  DistrictRP.reparto.aziende:
    default: op
  DistrictRP.reparto.fdo:
    default: op
  DistrictRP.reparto.criminalita:
    default: op
  DistrictRP.reparto.economia:
    default: op
  DistrictRP.appuntamenti.aziende:
    default: op
  DistrictRP.appuntamenti.criminalita:
    default: op
  DistrictRP.appuntamenti.economia:
    default: op
  DistrictRP.appuntamenti.marketing:
    default: op
  DistrictRP.appuntamenti.eventi:
    default: op
  DistrictRP.protection.admin:
    default: op
  DistrictRP.protection.bypass:
    default: op
  DistrictRP.rank.fondatore:
    default: false
  DistrictRP.rank.admin:
    default: false
  DistrictRP.rank.srmod:
    default: false
  DistrictRP.rank.mod:
    default: false
  DistrictRP.rank.helper:
    default: false
  DistrictRP.rank.tutor:
    default: false
  DistrictRP.rank.developer:
    default: false
  DistrictRP.rank.builder:
    default: false
  DistrictRP.rank.texturemaker:
    default: false
  DistrictRP.rank.staff:
    default: false